### ISSUE TITLE
Dancing

### ISSUE THREAD

**Issue by AlphaWolf294** [Boostvolt/tesla_modelx#1]
There is an issue with the "/tesla dance" command. Whenever I get into my Model X and do "/tesla dance" it says "Unknown vehicle".

Edit: No matter the option I try it says unknown vehicle. It is the only Model X in the game so it is 99% likely to be yours'.

**Comment by Boostvolt** [comment]
Thanks for the note, I have just fixed the bug. Please use version 1.3.0: [https://github.com/Boostvolt/tesla_functions/releases/tag/1.3](https://github.com/Boostvolt/tesla_functions/releases/tag/1.3).
